### PR TITLE
fix: add addl context from manifests

### LINKED ISSUE #65: Natural Language Configuration Edits
I think it would be the best UX to edit the behavior (config) of UbiquityOS just by telling it. For example:

@UbiquityOS change the base score of all images in text-conversation-rewards from 5 to 10. 

I have a functional implementation [here](https://github.com/0x4007/sync-configs-agent) which works both from CLI and from the GitHub Actions dispatcher. The only capability that needs to be added potentially in the context of this plugin is to understand which repository is being worked on, and to edit the current repository's config (or if there is none, then the organization config.)

This implementation needs to be wrapped inside of a plugin. 

### Previous Context

https://github.com/ubiquity/ubiquity-dollar/issues/964#issuecomment-2403859462

Good scenario to test:

"@UbiquityOS in conversation rewards, you must manually initialize all the html tag defaults."

Should yield something like https://github.com/Ubiquity-DAO/ubiquibot-config/commit/133419d51295c85e843a75f9f8ef63a0622ea0db

After it successfully made the change (non interactive mode) it should automatically link back a pull

It must also check if you're an admin before being able to change the configuration.

### PR DESCRIPTION
**Pull request by shiv810**
Resolves [#65](https://github.com/ubiquity-os/plugins-wishlist/issues/65)

### CODE REVIEW

File: src/helpers/target-scope.ts [hunk 1]
```diff
@@ -2,33 +2,43 @@ import path from "path";
...
+    // Check Access to the base targets
+    const hasPermission = await checkUserRepoPermissions(context, owner, repo);
+
+    baseTargets.push({
       type: target.type || "main",
       owner,
       repo,
       localDir: path.join(owner, repo),
       url: target.name,
+      scope: target.scope === "REPO" ? Scope.REPO : Scope.ORG,
```
Comment (0x4007) [inline src/helpers/target-scope.ts]: This should definitely be implicit. Just check if repo config exists, if not, then org. The user doesn't need to specify this.

File: src/handlers/sync-config.ts [hunk 2]
```diff
@@ -45,13 +37,46 @@ export async function syncConfigs(context: Context) {
...
     const prList = prUrls
-      .map((url, i) => {
-        const prNumber = url.split("/").pop();
-        return `${i + 1}. [${prNumber}](${url})`;
+      .map((url) => {
+        return `- ${url}`;
       })
       .join("\n");
-    const message = `✅ Successfully created ${prUrls.length} pull request${pluralSuffix}:\n\n${prList}`;
+    const message = `Successfully created ${prUrls.length} pull request${pluralSuffix}:\n\n${prList}`;
```
Comment (0x4007) [inline src/handlers/sync-config.ts]: This is redundant and should be removed. It's clear the pull request is made successfully because the link and icon is right next to it.

File: src/adapters/openai/completions.ts [hunk 3]
```diff
@@ -42,11 +43,21 @@ When making changes to plugin configurations, maintain this structure:
...
     property1: value1
     property2: value2
 
+PLUGIN INSTRUCTIONS:
+- Ensure all plugin configurations are correctly formatted
+- Use the manifests below to understand valid plugin properties and default values
+- Do not remove any existing plugin configurations unless instructed
+- Add new plugin configurations at the end of the file
+- Infer ORG/OWNER and REPO details from the included plugin configurations and manifests
+- DO NOT HALLUCINATE PLUGIN CONFIGURATIONS ALWAYS REFER TO THE MANIFESTS.
```
Comment (0x4007) [inline src/adapters/openai/completions.ts]: I'm not sure that "do not hallucinate" is valid prompt material

File: src/adapters/git/super/actions/pull-request.ts [hunk 4]
```diff
@@ -71,15 +63,16 @@ export class PullRequest extends GitSuper {
...
 
-      // Create pull request
+      // Create pull request with initial body
       const { data: pr } = await this._context.octokit.rest.pulls.create({
         owner,
         repo,
-        title: `Update ${filePath}`,
-        body: "Automated update using autoedit",
+        title: `chore: update \`${filePath}\``,
+        body: `Update to \`${filePath}\` following this instruction:\n\n
```
Comment (0x4007) [inline src/adapters/git/super/actions/pull-request.ts]: This is redundant because all the same information is in the title. As requested before you should do something like how I had it, which contained the original query and it also said who ran it. 

Given that you enabled support to run this from a GitHub comment, it might be nice to link back to the original comment as well.

File: manifest.json [hunk 5]
```diff
@@ -3,9 +3,9 @@
   "description": "ts-template for UbiquityOS plugins.",
   "ubiquity:listeners": ["issue_comment.created", "pull_request_review_comment.created"],
   "commands": {
-    "autoedit": {
-      "ubiquity:example": "/autoedit argument",
-      "description": "autoedit command with an argument."
+    "config": {
+      "ubiquity:example": "/config <scope> <editor_instruction>",
```
Comment (0x4007) [inline manifest.json]: Scope should be removed read below

**Review by 0x4007 — CHANGES_REQUESTED** [review]

File: src/helpers/target-scope.ts (hunk 1 above)
Comment (shiv810) [reply src/helpers/target-scope.ts]: If the user specifies /config <Editor_Instruction>, in case 1, if both org and repo configs are available, a PR will be created for both. In case 2, if only the org or repo config is available, a PR will be created for the available one. Is that correct?

Comment (0x4007) [reply src/helpers/target-scope.ts]: Yes basically always pick repo config if it exists. Otherwise, fallback to the org config.

File: src/adapters/openai/completions.ts (hunk 3 above)
Comment (shiv810) [reply src/adapters/openai/completions.ts]: I mean it is, Apple used this in their prompt, not sure about its efficacy.

File: src/adapters/git/super/actions/pull-request.ts (hunk 4 above)
Comment (shiv810) [reply src/adapters/git/super/actions/pull-request.ts]: Fixed, Refer to QA

File: manifest.json (hunk 5 above)
Comment (shiv810) [reply manifest.json]: Removed, auto scope infer, Refer QA

**Comment by shiv810** [comment]
QA:

Repo Scope (Config Present at the repo level):

- https://github.com/ShivTestOrg/test-public/issues/275#issuecomment-2720152601

Org Scope

- https://github.com/ShivTestOrg/text-conversation-rewards/issues/1#issuecomment-2720170544

File: src/adapters/openai/completions.ts (hunk 3 above)
Comment (0x4007) [reply src/adapters/openai/completions.ts]: Apple is not known for their AI prowess. Quite the opposite actually. Anthropic and OpenAI are much better for reference.

Comment (0x4007) [reply src/adapters/openai/completions.ts]: We need evals to improve the prompt.

File: manifest.json [hunk 6]
```diff
@@ -1,11 +1,17 @@
 {
-  "name": "ts-template",
-  "description": "ts-template for UbiquityOS plugins.",
+  "name": "autoedit",
+  "description": "Edits configs based on natural language commands.",
```
Comment (0x4007) [inline manifest.json]:
```suggestion
  "description": "Edits UbiquityOS configuration files based on natural language queries.",
```

File: package.json [hunk 7]
```diff
@@ -1,5 +1,5 @@
 {
-  "name": "plugin-template",
+  "name": "@ubiquity-os/autoedit",
```
Comment (0x4007) [inline package.json]:
```suggestion
  "name": "@ubiquity-os-marketplace/command-config",
```

File: package.json [hunk 8]
```diff
@@ -21,7 +21,7 @@
     "knip": "knip --config .github/knip.ts",
     "knip-ci": "knip --no-exit-code --reporter json --config .github/knip.ts",
     "test": "cross-env NODE_OPTIONS=\"$NODE_OPTIONS --experimental-vm-modules\" jest --setupFiles dotenv/config --coverage",
-    "worker": "wrangler dev --env dev --port 4000",
+    "worker": "wrangler dev --env dev --port 4000 --ip 100.72.255.83",
```
Comment (0x4007) [inline package.json]: What's this IP

File: src/adapters/openai/completions.ts [hunk 9]
```diff
@@ -42,11 +43,21 @@ When making changes to plugin configurations, maintain this structure:
...
     property2: value2
 
+PLUGIN INSTRUCTIONS:
+- Ensure all plugin configurations are correctly formatted
+- Use the manifests below to understand valid plugin properties and default values
+- Do not remove any existing plugin configurations unless instructed
+- Add new plugin configurations at the end of the file
+- Infer ORG/OWNER and REPO details from the included plugin configurations and manifests
+- DO NOT REMOVE CONTENT UNLESS SPECIFICALLY INSTRUCTED TO DO SO
+- ALWAYS TARGET MAIN BRANCH FOR PLUGIN CONFIGURATIONS, UNLESS SPECIFIED OTHERWISE.
```
Comment (0x4007) [inline src/adapters/openai/completions.ts]: This is not always true. Default branch is always true. I'm pretty sure our default branch on @ubiquity is `development`.

File: src/adapters/openai/completions.ts [hunk 10]
```diff
@@ -58,10 +69,18 @@ The YAML parser that will be used to validate your output is shown below. Ensure
 
       parserCode,
 
-      `REFERENCE MANIFESTS:
+      `IMPORTANT CONTEXT MANIFESTS:
```
Comment (0x4007) [inline src/adapters/openai/completions.ts:71]: How did you come to this conclusion that this change is needed?

**Review by 0x4007 — APPROVED** [review]
Please address my last changes. @Whilefoo please do a retroactive review because we are about ready to test in production.

File: package.json (hunk 7 above)
Comment (0x4007) [reply package.json]: Change the project name reference everywhere appropriate.

File: src/adapters/openai/completions.ts (hunk 10 above)
Comment (shiv810) [reply src/adapters/openai/completions.ts:71]: When I tried adding new plugin configurations, sometimes the manifests were ignored. Changing this to `IMPORTANT CONTEXT` caused the model to pick it up in most cases.

File: src/adapters/openai/completions.ts (hunk 9 above)
Comment (shiv810) [reply src/adapters/openai/completions.ts]: Removed this. I was under the assumption that @ubiquity uses `main`.

File: package.json (hunk 8 above)
Comment (shiv810) [reply package.json]: Removed.

File: package.json (hunk 7 above)
Comment (shiv810) [reply package.json]: Updated the project name
